AllCops:
  Exclude:
    - 'db/**/*'
    - 'spec/**/*'
    - 'lib/desmond/migrations/**/*'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false
