app_id: desmond # id of the app using desmond
database: config/database.yml # where does the database configuration reside
system_connection_allowed: false # whether the tasks are allowed to use the configured
                                 # connection instead of using the users credentials
