access_key_id: access_key # aws access key to use for requests
secret_access_key: secret_key # aws secret key to use for requests
export_bucket: export-bucket # bucket to be used for exports
import_bucket: import-bucket # bucket to be used for imports
import_schema: schema # RedShift schema to use for importing
